KNP-8 Custom Fetch
frontend-park-mail-ru/2024_1_Cyberkotletki pull request #10
Opened 2024-03-24 16:48 UTC by blackHATred

2024-03-24 20:16 UTC, EGRoBBeRTiT commented
Коммит нужно делать так:
`git add .`, затем
`npm run commit`, не `git commit -m ""`. 
А то я смотрю коммит опять сделать не по стандарту

2024-03-24 21:02 UTC, blackHATred commented
> Коммит нужно делать так: `git add .`, затем `npm run commit`, не `git commit -m ""`. А то я смотрю коммит опять сделать не по стандарту

Я коммиты делаю посредством стандартных инструментов в Jetbrains. Могу делать через команды, но в чём принципиальная разница между `git add .` и `npm run commit` + `git commit -m ""`?

2024-03-24 21:44 UTC, EGRoBBeRTiT requested changes

2024-03-24 21:44 UTC, EGRoBBeRTiT commented on src/api/auth/routes.ts
> +    isAuth = (): string => '/auth/isAuth';
Добавь ко всем роутам as const  после строки
`isAuth = (): string => '/auth/isAuth' as const;`

2024-03-24 21:44 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +        if (options.queryParams !== undefined) {
Тут просто `if (options.queryParams)`

2024-03-24 21:44 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +                params.append(key, value);
Оберни value в encodeURIComponent, чтобы закодировать нелатинские значения, если они вдруг придут

2024-03-24 21:44 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +            url = `${baseURL + url}?${params.toString()}`;
Функция нечистая получилась. Если передашь в нее константную строку, то она изменится и при следующем ее применении неизвестно, что в этой строке будет. Создай переменную до условий и присвой url, затем здесь `customUrl += '?${params.toString()}'`

2024-03-24 21:44 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +            url = `${baseURL + url}`;
То же самое

2024-03-24 21:44 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +            options.jsonData !== undefined &&
просто `options.jsonData && ...`

2024-03-24 21:44 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +        clearTimeout(id);
Тут clearTimeout вызовется синхронно сразу же после объвления response, и получается, что смысла в controller.abort() нету, это тоже самое, если написать 

```js
const id = setTimeout(() => controller.abort(), options.timeout);
clearTimeout(id);
```

Если цель в том, чтобы прервать fetch если запрос выполняется дольше options.timeout, то clearTimeout вообще нужно убрать, но его точно нужно добавить в fetch.finally

2024-03-24 21:44 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +    const request = async (url: string, options: RequestParams) => {
Здесь стоит добавить generic для ответа и для body
```ts
const request = async <Body extends object, T>(url: string, options: RequestParams<Body>)
```
затем T использовать в fetch `...body.json() as T`

2024-03-24 21:44 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +        });
Здесь лучше добавить `.then((body)=>body.json() as T)`, а то везде придется вызывать json()

2024-03-24 21:44 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +        post: (
Добавь еще уж и patch, put, delete

2024-03-24 21:44 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +interface RequestParams {
Добавь generic для jsonData (я бы переименовал на body))), чтобы body был нормально типизирован
```ts
interface RequestParams<T extends object> {
    url: string;
    method: string;
    useCookies?: boolean;
    timeout?: number;
    headers?: Record<string, string>;
    queryParams?: Record<string, string>;
    jsonData?: T;
}
```

2024-03-24 21:44 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +        get: (
В этих функциях придется добавить дженерики и пробросить их в request

2024-03-24 21:44 UTC, EGRoBBeRTiT commented on src/api/auth/service.ts
> +            .post(authRoutes.login(), {
`appFetch.post<Body, Response>(...` вместо `Promise<AuthResponse>`, что находится выше, а для body тоже тип напиши

2024-03-24 21:44 UTC, EGRoBBeRTiT commented on src/api/auth/service.ts
> +                    case 400:
Используй RESPONSE_ERROR_CODE вместо просто 400, и измени везде

2024-03-24 21:44 UTC, EGRoBBeRTiT commented on src/api/auth/constants.ts
> +};
добавь в конце as const

2024-03-24 21:44 UTC, EGRoBBeRTiT commented on src/components/Cards/FilmCard.js
> +    getFilm = (id) => {
Я эти места фиксил в мре knp-3, посмотри, чтобы конфликты фиксить не пришлось

2024-03-24 21:48 UTC, EGRoBBeRTiT commented
> > Коммит нужно делать так: `git add .`, затем `npm run commit`, не `git commit -m ""`. А то я смотрю коммит опять сделать не по стандарту
> 
> Я коммиты делаю посредством стандартных инструментов в Jetbrains. Могу делать через команды, но в чём принципиальная разница между `npm run commit` и `git commit -m ""`?

Разница в том, что перед коммитом проходят все линтеры и запускается билд, чтобы не запушить ошибки, а так же коммиты приобретают общий вид, можешь посмотреть на мои коммиты: "fix(knp-3):  message", такой коммит получается автоматически. [Здесь](https://www.conventionalcommits.org/ru/v1.0.0-beta.4/) можно почитать поподробнее

2024-03-25 15:37 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +interface RequestParams<T extends object> {
Раз будет multipart/form-data, то убери extends object

2024-03-25 15:37 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +export const ResponseStatus = {
Используй из shared/constants

2024-03-25 15:37 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +        post: <Body extends object, Response>(
Еще методы, про которые говорили

2024-03-25 15:37 UTC, EGRoBBeRTiT commented on src/api/auth/constants.ts
> +};
Чтобы к каждой строке не дописывать as const, можно  просто после объекта это написать

2024-03-25 15:37 UTC, EGRoBBeRTiT commented on src/api/auth/service.ts
> +            .post<LoginPayload, string>(authRoutes.login(), {
А как линтер прошел... 
Тут же в body явно не string а `{login: string, password: string}`

2024-03-25 15:37 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +                            ? (response.json() as Promise<T>)
Тут  просто `T`, не `Promise<T>`, иначе получается, что функция возрвращает  `Promise<Promise<T>>`

2024-03-25 15:37 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +                const contentType = response.headers.get('content-type');
Можно сделать проверку на response.ok + throw, про который говорили

2024-03-25 15:37 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +        get: <Response>(
Тут Body нету, в get запросах спокойно может быть body

2024-03-25 15:37 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
>              request(url, {
вместо того, чтобы писать `: Promise<{ status: number; data: Promise<Response> }>`, нужно 
`... => request<Body, { status: number; data: Response }>(url, ...)`
и Promise у data нужно убрать, тут же ожидается объект Response, про который я ниже написал, и если он пришел, то data там уже есть и ее еще ожидать не надо

2024-03-25 15:37 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
>              request(url, {
И раз у тебя шаблон ответа, то вынеси его в тип
 ```ts
 interface Response<T> {
    status: number,
    data: T
}
 ```

2024-03-25 15:37 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +        ): Promise<{ status: number; data: Promise<Response> }> =>
`request<Body, Response<T>>`

2024-03-25 15:37 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +                body: jsonData,
Чтобы было меньше когда, переименуй jsonData в body

2024-03-25 15:42 UTC, blackHATred commented on src/api/applicationFetch.ts
> +        get: <Response>(
Может, но это bad practice и противоречит стандартам. Обычно веб-серверы, даже если им отправить get с body, могут заигнорить тело

2024-03-25 15:44 UTC, blackHATred commented on src/api/applicationFetch.ts
> +        get: <Response>(
https://developer.mozilla.org/ru/docs/Web/HTTP/Methods/GET

2024-03-25 15:45 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +        get: <Response>(
Тут смотря какой бек, вполне может быть, что я захочу что-то получить, и при этом в body бэк хочет увидеть какие-то данные. Такую возможность учитывать надо

2024-03-25 15:49 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +        get: <Response>(
> https://developer.mozilla.org/ru/docs/Web/HTTP/Methods/GET
Ну как скажешь) У нас бек не будет принимать body

2024-03-25 17:45 UTC, EGRoBBeRTiT requested changes

2024-03-25 17:45 UTC, EGRoBBeRTiT commented on src/api/applicationFetch.ts
> +export default appFetch;
Сделай именной экспорт и переименуй файл на appFetch раз экспортируешь appFetch, чтобы названия совпадали

2024-03-25 21:46 UTC, EGRoBBeRTiT requested changes

2024-03-25 21:46 UTC, EGRoBBeRTiT commented on webpack.config.js
> +        extensions: ['.tsx', '.ts', '.d.ts', '.js'],
Думаю, это нужно убрать, '.ts' перекрывает '.d.ts'

2024-03-25 21:46 UTC, EGRoBBeRTiT commented on src/api/appFetch.ts
> +        post: <Body extends object, ResponseT>(
Только сейчас заметил. Так как у нас будет form data, то extends object нужно убрать

2024-03-25 21:46 UTC, EGRoBBeRTiT commented on src/api/appFetch.ts
> +        put: <Body extends object, ResponseT>(
И здесь

2024-03-25 21:46 UTC, EGRoBBeRTiT commented on src/api/appFetch.ts
> +        patch: <Body extends object, ResponseT>(
и здесь

2024-03-25 21:46 UTC, EGRoBBeRTiT commented on src/api/appFetch.ts
> +        delete: <Body extends object, ResponseT>(
и здесь

2024-03-25 21:46 UTC, EGRoBBeRTiT commented on src/api/appFetch.ts
> +        ): Promise<FetchResponse<ResponseT>> =>
Лучше не лишний раз не писать то, что функция возвращает, а то можно ошибиться, написать одно, а функция возвращает другое.
Тут лучше передать типы в request, и при наведении на request ты увидишь тип, который возвращается 
```ts
request<void, ResponseT>(url...)
```

2024-03-25 21:46 UTC, EGRoBBeRTiT commented on src/api/appFetch.ts
> +    const request = async <Body extends object, T>(
тут тоже extends object нужно убрать

2024-03-25 21:46 UTC, EGRoBBeRTiT commented on src/api/appFetch.ts
> +            request(url, {
```ts
request< Body, ResponseT>(url...)
```

2024-03-25 21:46 UTC, EGRoBBeRTiT commented on src/api/appFetch.ts
> +            request(url, {
```ts
request< Body, ResponseT>(url...)
```

2024-03-25 21:46 UTC, EGRoBBeRTiT commented on src/api/appFetch.ts
> +            request(url, {
```ts
request< Body, FetchResponse<ResponseT>>(url...)
```

2024-03-25 21:46 UTC, EGRoBBeRTiT commented on src/api/appFetch.ts
> +            request(url, {
```ts
request< Body, ResponseT>(url...)
```

2024-03-25 21:46 UTC, EGRoBBeRTiT commented on src/api/appFetch.ts
> +
Я думал ты здесь сделаешь проверку на response.ok, и выбросишь ошибку

2024-03-26 15:58 UTC, blackHATred commented on webpack.config.js
> +        extensions: ['.tsx', '.ts', '.d.ts', '.js'],
Я не просто так это добавил, без этого вебпак выкидывает ошибку, т.к. не видит файлы с константами. Можно конечно файлы с const-ми делать просто .ts, а не .d.ts, но это плохо, насколько я понимаю)

2024-03-26 16:22 UTC, EGRoBBeRTiT approved these changes

2024-04-07 15:56 UTC, merged